apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: js-carla # Change this to your js
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 256Gi
